  name: 'A ci pipleline for auth-server'
  on:
    workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Go environment
          uses: actions/setup-go@v5.0.0
          with:
            go-version: '>=1.21.0'
        - name: Compile
          run: |
            make build docker=true os=linux


