  name: 'A ci pipleline for auth-server'
  on:
    workflow_dispatch:
    push:
      branches:
        - master
  jobs:
    build:
      environment: dev
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Go environment
          uses: actions/setup-go@v5.0.0
          with:
            go-version: '>=1.21.0'
            check-latest: true
            cache-dependency-path: |
              subdir/go.sum
              tools/go.sum
        - name: Compile
          run: |
            make build docker=true
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Push the image to Docker Hub
          run: |
            make push


